// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface GetDistributionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDistributionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double distributionValue = 1;</code>
   */
  double getDistributionValue();
}
