// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface GetDistributionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDistributionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keyName = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string keyName = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>double percentileValue = 2;</code>
   */
  double getPercentileValue();
}
