// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

/**
 * Protobuf type {@code InventoryRecord}
 */
public  final class InventoryRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InventoryRecord)
    InventoryRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InventoryRecord.newBuilder() to construct.
  private InventoryRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InventoryRecord() {
    name_ = "";
    description_ = "";
    unitPrice_ = "";
    quantityInStock_ = 0;
    inventoryValue_ = 0;
    reorderLevel_ = 0;
    reorderTimeInDays_ = 0;
    quantityInReorder_ = 0;
    discontinued_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InventoryRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            unitPrice_ = s;
            break;
          }
          case 32: {

            quantityInStock_ = input.readInt32();
            break;
          }
          case 40: {

            inventoryValue_ = input.readInt32();
            break;
          }
          case 48: {

            reorderLevel_ = input.readInt32();
            break;
          }
          case 56: {

            reorderTimeInDays_ = input.readInt32();
            break;
          }
          case 64: {

            quantityInReorder_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            discontinued_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_InventoryRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_InventoryRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            example.myapp.inventory.grpc.InventoryRecord.class, example.myapp.inventory.grpc.InventoryRecord.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 2;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNITPRICE_FIELD_NUMBER = 3;
  private volatile java.lang.Object unitPrice_;
  /**
   * <code>string unitPrice = 3;</code>
   */
  public java.lang.String getUnitPrice() {
    java.lang.Object ref = unitPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unitPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string unitPrice = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUnitPriceBytes() {
    java.lang.Object ref = unitPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unitPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITYINSTOCK_FIELD_NUMBER = 4;
  private int quantityInStock_;
  /**
   * <code>int32 quantityInStock = 4;</code>
   */
  public int getQuantityInStock() {
    return quantityInStock_;
  }

  public static final int INVENTORYVALUE_FIELD_NUMBER = 5;
  private int inventoryValue_;
  /**
   * <code>int32 inventoryValue = 5;</code>
   */
  public int getInventoryValue() {
    return inventoryValue_;
  }

  public static final int REORDERLEVEL_FIELD_NUMBER = 6;
  private int reorderLevel_;
  /**
   * <code>int32 reorderLevel = 6;</code>
   */
  public int getReorderLevel() {
    return reorderLevel_;
  }

  public static final int REORDERTIMEINDAYS_FIELD_NUMBER = 7;
  private int reorderTimeInDays_;
  /**
   * <code>int32 reorderTimeInDays = 7;</code>
   */
  public int getReorderTimeInDays() {
    return reorderTimeInDays_;
  }

  public static final int QUANTITYINREORDER_FIELD_NUMBER = 8;
  private int quantityInReorder_;
  /**
   * <code>int32 quantityInReorder = 8;</code>
   */
  public int getQuantityInReorder() {
    return quantityInReorder_;
  }

  public static final int DISCONTINUED_FIELD_NUMBER = 9;
  private volatile java.lang.Object discontinued_;
  /**
   * <code>string discontinued = 9;</code>
   */
  public java.lang.String getDiscontinued() {
    java.lang.Object ref = discontinued_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      discontinued_ = s;
      return s;
    }
  }
  /**
   * <code>string discontinued = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDiscontinuedBytes() {
    java.lang.Object ref = discontinued_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      discontinued_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (!getUnitPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, unitPrice_);
    }
    if (quantityInStock_ != 0) {
      output.writeInt32(4, quantityInStock_);
    }
    if (inventoryValue_ != 0) {
      output.writeInt32(5, inventoryValue_);
    }
    if (reorderLevel_ != 0) {
      output.writeInt32(6, reorderLevel_);
    }
    if (reorderTimeInDays_ != 0) {
      output.writeInt32(7, reorderTimeInDays_);
    }
    if (quantityInReorder_ != 0) {
      output.writeInt32(8, quantityInReorder_);
    }
    if (!getDiscontinuedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, discontinued_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (!getUnitPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, unitPrice_);
    }
    if (quantityInStock_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quantityInStock_);
    }
    if (inventoryValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, inventoryValue_);
    }
    if (reorderLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, reorderLevel_);
    }
    if (reorderTimeInDays_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, reorderTimeInDays_);
    }
    if (quantityInReorder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, quantityInReorder_);
    }
    if (!getDiscontinuedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, discontinued_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof example.myapp.inventory.grpc.InventoryRecord)) {
      return super.equals(obj);
    }
    example.myapp.inventory.grpc.InventoryRecord other = (example.myapp.inventory.grpc.InventoryRecord) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getUnitPrice()
        .equals(other.getUnitPrice());
    result = result && (getQuantityInStock()
        == other.getQuantityInStock());
    result = result && (getInventoryValue()
        == other.getInventoryValue());
    result = result && (getReorderLevel()
        == other.getReorderLevel());
    result = result && (getReorderTimeInDays()
        == other.getReorderTimeInDays());
    result = result && (getQuantityInReorder()
        == other.getQuantityInReorder());
    result = result && getDiscontinued()
        .equals(other.getDiscontinued());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + UNITPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getUnitPrice().hashCode();
    hash = (37 * hash) + QUANTITYINSTOCK_FIELD_NUMBER;
    hash = (53 * hash) + getQuantityInStock();
    hash = (37 * hash) + INVENTORYVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getInventoryValue();
    hash = (37 * hash) + REORDERLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getReorderLevel();
    hash = (37 * hash) + REORDERTIMEINDAYS_FIELD_NUMBER;
    hash = (53 * hash) + getReorderTimeInDays();
    hash = (37 * hash) + QUANTITYINREORDER_FIELD_NUMBER;
    hash = (53 * hash) + getQuantityInReorder();
    hash = (37 * hash) + DISCONTINUED_FIELD_NUMBER;
    hash = (53 * hash) + getDiscontinued().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(example.myapp.inventory.grpc.InventoryRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InventoryRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InventoryRecord)
      example.myapp.inventory.grpc.InventoryRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_InventoryRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_InventoryRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.myapp.inventory.grpc.InventoryRecord.class, example.myapp.inventory.grpc.InventoryRecord.Builder.class);
    }

    // Construct using example.myapp.inventory.grpc.InventoryRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      description_ = "";

      unitPrice_ = "";

      quantityInStock_ = 0;

      inventoryValue_ = 0;

      reorderLevel_ = 0;

      reorderTimeInDays_ = 0;

      quantityInReorder_ = 0;

      discontinued_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_InventoryRecord_descriptor;
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.InventoryRecord getDefaultInstanceForType() {
      return example.myapp.inventory.grpc.InventoryRecord.getDefaultInstance();
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.InventoryRecord build() {
      example.myapp.inventory.grpc.InventoryRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.InventoryRecord buildPartial() {
      example.myapp.inventory.grpc.InventoryRecord result = new example.myapp.inventory.grpc.InventoryRecord(this);
      result.name_ = name_;
      result.description_ = description_;
      result.unitPrice_ = unitPrice_;
      result.quantityInStock_ = quantityInStock_;
      result.inventoryValue_ = inventoryValue_;
      result.reorderLevel_ = reorderLevel_;
      result.reorderTimeInDays_ = reorderTimeInDays_;
      result.quantityInReorder_ = quantityInReorder_;
      result.discontinued_ = discontinued_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof example.myapp.inventory.grpc.InventoryRecord) {
        return mergeFrom((example.myapp.inventory.grpc.InventoryRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(example.myapp.inventory.grpc.InventoryRecord other) {
      if (other == example.myapp.inventory.grpc.InventoryRecord.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getUnitPrice().isEmpty()) {
        unitPrice_ = other.unitPrice_;
        onChanged();
      }
      if (other.getQuantityInStock() != 0) {
        setQuantityInStock(other.getQuantityInStock());
      }
      if (other.getInventoryValue() != 0) {
        setInventoryValue(other.getInventoryValue());
      }
      if (other.getReorderLevel() != 0) {
        setReorderLevel(other.getReorderLevel());
      }
      if (other.getReorderTimeInDays() != 0) {
        setReorderTimeInDays(other.getReorderTimeInDays());
      }
      if (other.getQuantityInReorder() != 0) {
        setQuantityInReorder(other.getQuantityInReorder());
      }
      if (!other.getDiscontinued().isEmpty()) {
        discontinued_ = other.discontinued_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      example.myapp.inventory.grpc.InventoryRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (example.myapp.inventory.grpc.InventoryRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object unitPrice_ = "";
    /**
     * <code>string unitPrice = 3;</code>
     */
    public java.lang.String getUnitPrice() {
      java.lang.Object ref = unitPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unitPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string unitPrice = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUnitPriceBytes() {
      java.lang.Object ref = unitPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unitPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string unitPrice = 3;</code>
     */
    public Builder setUnitPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      unitPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string unitPrice = 3;</code>
     */
    public Builder clearUnitPrice() {
      
      unitPrice_ = getDefaultInstance().getUnitPrice();
      onChanged();
      return this;
    }
    /**
     * <code>string unitPrice = 3;</code>
     */
    public Builder setUnitPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      unitPrice_ = value;
      onChanged();
      return this;
    }

    private int quantityInStock_ ;
    /**
     * <code>int32 quantityInStock = 4;</code>
     */
    public int getQuantityInStock() {
      return quantityInStock_;
    }
    /**
     * <code>int32 quantityInStock = 4;</code>
     */
    public Builder setQuantityInStock(int value) {
      
      quantityInStock_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantityInStock = 4;</code>
     */
    public Builder clearQuantityInStock() {
      
      quantityInStock_ = 0;
      onChanged();
      return this;
    }

    private int inventoryValue_ ;
    /**
     * <code>int32 inventoryValue = 5;</code>
     */
    public int getInventoryValue() {
      return inventoryValue_;
    }
    /**
     * <code>int32 inventoryValue = 5;</code>
     */
    public Builder setInventoryValue(int value) {
      
      inventoryValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 inventoryValue = 5;</code>
     */
    public Builder clearInventoryValue() {
      
      inventoryValue_ = 0;
      onChanged();
      return this;
    }

    private int reorderLevel_ ;
    /**
     * <code>int32 reorderLevel = 6;</code>
     */
    public int getReorderLevel() {
      return reorderLevel_;
    }
    /**
     * <code>int32 reorderLevel = 6;</code>
     */
    public Builder setReorderLevel(int value) {
      
      reorderLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reorderLevel = 6;</code>
     */
    public Builder clearReorderLevel() {
      
      reorderLevel_ = 0;
      onChanged();
      return this;
    }

    private int reorderTimeInDays_ ;
    /**
     * <code>int32 reorderTimeInDays = 7;</code>
     */
    public int getReorderTimeInDays() {
      return reorderTimeInDays_;
    }
    /**
     * <code>int32 reorderTimeInDays = 7;</code>
     */
    public Builder setReorderTimeInDays(int value) {
      
      reorderTimeInDays_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reorderTimeInDays = 7;</code>
     */
    public Builder clearReorderTimeInDays() {
      
      reorderTimeInDays_ = 0;
      onChanged();
      return this;
    }

    private int quantityInReorder_ ;
    /**
     * <code>int32 quantityInReorder = 8;</code>
     */
    public int getQuantityInReorder() {
      return quantityInReorder_;
    }
    /**
     * <code>int32 quantityInReorder = 8;</code>
     */
    public Builder setQuantityInReorder(int value) {
      
      quantityInReorder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantityInReorder = 8;</code>
     */
    public Builder clearQuantityInReorder() {
      
      quantityInReorder_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object discontinued_ = "";
    /**
     * <code>string discontinued = 9;</code>
     */
    public java.lang.String getDiscontinued() {
      java.lang.Object ref = discontinued_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discontinued_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string discontinued = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDiscontinuedBytes() {
      java.lang.Object ref = discontinued_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discontinued_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string discontinued = 9;</code>
     */
    public Builder setDiscontinued(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      discontinued_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string discontinued = 9;</code>
     */
    public Builder clearDiscontinued() {
      
      discontinued_ = getDefaultInstance().getDiscontinued();
      onChanged();
      return this;
    }
    /**
     * <code>string discontinued = 9;</code>
     */
    public Builder setDiscontinuedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      discontinued_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InventoryRecord)
  }

  // @@protoc_insertion_point(class_scope:InventoryRecord)
  private static final example.myapp.inventory.grpc.InventoryRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new example.myapp.inventory.grpc.InventoryRecord();
  }

  public static example.myapp.inventory.grpc.InventoryRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryRecord>
      PARSER = new com.google.protobuf.AbstractParser<InventoryRecord>() {
    @java.lang.Override
    public InventoryRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InventoryRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InventoryRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public example.myapp.inventory.grpc.InventoryRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

