// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public final class InventoryRecordProto {
  private InventoryRecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InventoryRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InventoryRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddInventoryRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddInventoryRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateInventoryAttributeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateInventoryAttributeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchByIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchByIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchByKeyValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchByKeyValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDistributionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDistributionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDistributionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDistributionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\032\033google/protobuf/empty" +
      ".proto\"\332\001\n\017InventoryRecord\022\014\n\004name\030\001 \001(\t" +
      "\022\023\n\013description\030\002 \001(\t\022\021\n\tunitPrice\030\003 \001(\t" +
      "\022\027\n\017quantityInStock\030\004 \001(\005\022\026\n\016inventoryVa" +
      "lue\030\005 \001(\005\022\024\n\014reorderLevel\030\006 \001(\005\022\031\n\021reord" +
      "erTimeInDays\030\007 \001(\005\022\031\n\021quantityInReorder\030" +
      "\010 \001(\005\022\024\n\014discontinued\030\t \001(\t\"I\n\031AddInvent" +
      "oryRecordRequest\022\n\n\002ID\030\001 \001(\t\022 \n\006record\030\002" +
      " \001(\0132\020.InventoryRecord\"[\n\037UpdateInventor" +
      "yAttributeRequest\022\017\n\007keyName\030\001 \001(\t\022\025\n\rat" +
      "tributeName\030\002 \001(\t\022\020\n\010newValue\030\003 \001(\t\"\037\n\021S" +
      "earchByIDRequest\022\n\n\002ID\030\001 \001(\t\"2\n\016SearchRe" +
      "sponse\022 \n\006record\030\001 \001(\0132\020.InventoryRecord" +
      "\"<\n\027SearchByKeyValueRequest\022\017\n\007keyName\030\001" +
      " \001(\t\022\020\n\010keyValue\030\002 \001(\t\"B\n\026GetDistributio" +
      "nRequest\022\017\n\007keyName\030\001 \001(\t\022\027\n\017percentileV" +
      "alue\030\002 \001(\001\"4\n\027GetDistributionResponse\022\031\n" +
      "\021distributionValue\030\001 \001(\001\"Q\n\022SearchRangeR" +
      "equest\022\017\n\007keyName\030\001 \001(\t\022\025\n\rkeyStartValue" +
      "\030\002 \001(\t\022\023\n\013keyEndValue\030\003 \001(\t\"8\n\023SearchRan" +
      "geResponse\022!\n\007records\030\001 \003(\0132\020.InventoryR" +
      "ecord2\237\003\n\020InventoryService\022H\n\022AddInvento" +
      "ryRecord\022\032.AddInventoryRecordRequest\032\026.g" +
      "oogle.protobuf.Empty\022T\n\030UpdateInventoryA" +
      "ttribute\022 .UpdateInventoryAttributeReque" +
      "st\032\026.google.protobuf.Empty\0221\n\nSearchByID" +
      "\022\022.SearchByIDRequest\032\017.SearchResponse\022=\n" +
      "\020SearchByKeyValue\022\030.SearchByKeyValueRequ" +
      "est\032\017.SearchResponse\022D\n\017GetDistribution\022" +
      "\027.GetDistributionRequest\032\030.GetDistributi" +
      "onResponse\0223\n\006Search\022\023.SearchRangeReques" +
      "t\032\024.SearchRangeResponseB6\n\034example.myapp" +
      ".inventory.grpcB\024InventoryRecordProtoP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_InventoryRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InventoryRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InventoryRecord_descriptor,
        new java.lang.String[] { "Name", "Description", "UnitPrice", "QuantityInStock", "InventoryValue", "ReorderLevel", "ReorderTimeInDays", "QuantityInReorder", "Discontinued", });
    internal_static_AddInventoryRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddInventoryRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddInventoryRecordRequest_descriptor,
        new java.lang.String[] { "ID", "Record", });
    internal_static_UpdateInventoryAttributeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UpdateInventoryAttributeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateInventoryAttributeRequest_descriptor,
        new java.lang.String[] { "KeyName", "AttributeName", "NewValue", });
    internal_static_SearchByIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SearchByIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchByIDRequest_descriptor,
        new java.lang.String[] { "ID", });
    internal_static_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_descriptor,
        new java.lang.String[] { "Record", });
    internal_static_SearchByKeyValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SearchByKeyValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchByKeyValueRequest_descriptor,
        new java.lang.String[] { "KeyName", "KeyValue", });
    internal_static_GetDistributionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetDistributionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDistributionRequest_descriptor,
        new java.lang.String[] { "KeyName", "PercentileValue", });
    internal_static_GetDistributionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetDistributionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDistributionResponse_descriptor,
        new java.lang.String[] { "DistributionValue", });
    internal_static_SearchRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_SearchRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRangeRequest_descriptor,
        new java.lang.String[] { "KeyName", "KeyStartValue", "KeyEndValue", });
    internal_static_SearchRangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SearchRangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRangeResponse_descriptor,
        new java.lang.String[] { "Records", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
