// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface InventoryRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InventoryRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string unitPrice = 3;</code>
   */
  java.lang.String getUnitPrice();
  /**
   * <code>string unitPrice = 3;</code>
   */
  com.google.protobuf.ByteString
      getUnitPriceBytes();

  /**
   * <code>int32 quantityInStock = 4;</code>
   */
  int getQuantityInStock();

  /**
   * <code>int32 inventoryValue = 5;</code>
   */
  int getInventoryValue();

  /**
   * <code>int32 reorderLevel = 6;</code>
   */
  int getReorderLevel();

  /**
   * <code>int32 reorderTimeInDays = 7;</code>
   */
  int getReorderTimeInDays();

  /**
   * <code>int32 quantityInReorder = 8;</code>
   */
  int getQuantityInReorder();

  /**
   * <code>string discontinued = 9;</code>
   */
  java.lang.String getDiscontinued();
  /**
   * <code>string discontinued = 9;</code>
   */
  com.google.protobuf.ByteString
      getDiscontinuedBytes();
}
