// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.InventoryRecord record = 1;</code>
   */
  boolean hasRecord();
  /**
   * <code>.InventoryRecord record = 1;</code>
   */
  example.myapp.inventory.grpc.InventoryRecord getRecord();
  /**
   * <code>.InventoryRecord record = 1;</code>
   */
  example.myapp.inventory.grpc.InventoryRecordOrBuilder getRecordOrBuilder();
}
