// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface SearchByIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchByIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ID = 1;</code>
   */
  java.lang.String getID();
  /**
   * <code>string ID = 1;</code>
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
