// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface SearchByKeyValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchByKeyValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keyName = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string keyName = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string keyValue = 2;</code>
   */
  java.lang.String getKeyValue();
  /**
   * <code>string keyValue = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyValueBytes();
}
