// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface SearchRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keyName = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string keyName = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string keyStartValue = 2;</code>
   */
  java.lang.String getKeyStartValue();
  /**
   * <code>string keyStartValue = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyStartValueBytes();

  /**
   * <code>string keyEndValue = 3;</code>
   */
  java.lang.String getKeyEndValue();
  /**
   * <code>string keyEndValue = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyEndValueBytes();
}
