// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

/**
 * Protobuf type {@code SearchRangeResponse}
 */
public  final class SearchRangeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SearchRangeResponse)
    SearchRangeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchRangeResponse.newBuilder() to construct.
  private SearchRangeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchRangeResponse() {
    records_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchRangeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              records_ = new java.util.ArrayList<example.myapp.inventory.grpc.InventoryRecord>();
              mutable_bitField0_ |= 0x00000001;
            }
            records_.add(
                input.readMessage(example.myapp.inventory.grpc.InventoryRecord.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        records_ = java.util.Collections.unmodifiableList(records_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_SearchRangeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_SearchRangeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            example.myapp.inventory.grpc.SearchRangeResponse.class, example.myapp.inventory.grpc.SearchRangeResponse.Builder.class);
  }

  public static final int RECORDS_FIELD_NUMBER = 1;
  private java.util.List<example.myapp.inventory.grpc.InventoryRecord> records_;
  /**
   * <code>repeated .InventoryRecord records = 1;</code>
   */
  public java.util.List<example.myapp.inventory.grpc.InventoryRecord> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .InventoryRecord records = 1;</code>
   */
  public java.util.List<? extends example.myapp.inventory.grpc.InventoryRecordOrBuilder> 
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .InventoryRecord records = 1;</code>
   */
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .InventoryRecord records = 1;</code>
   */
  public example.myapp.inventory.grpc.InventoryRecord getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .InventoryRecord records = 1;</code>
   */
  public example.myapp.inventory.grpc.InventoryRecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < records_.size(); i++) {
      output.writeMessage(1, records_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < records_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, records_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof example.myapp.inventory.grpc.SearchRangeResponse)) {
      return super.equals(obj);
    }
    example.myapp.inventory.grpc.SearchRangeResponse other = (example.myapp.inventory.grpc.SearchRangeResponse) obj;

    boolean result = true;
    result = result && getRecordsList()
        .equals(other.getRecordsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecordsCount() > 0) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static example.myapp.inventory.grpc.SearchRangeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(example.myapp.inventory.grpc.SearchRangeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SearchRangeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SearchRangeResponse)
      example.myapp.inventory.grpc.SearchRangeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_SearchRangeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_SearchRangeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              example.myapp.inventory.grpc.SearchRangeResponse.class, example.myapp.inventory.grpc.SearchRangeResponse.Builder.class);
    }

    // Construct using example.myapp.inventory.grpc.SearchRangeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecordsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return example.myapp.inventory.grpc.InventoryRecordProto.internal_static_SearchRangeResponse_descriptor;
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.SearchRangeResponse getDefaultInstanceForType() {
      return example.myapp.inventory.grpc.SearchRangeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.SearchRangeResponse build() {
      example.myapp.inventory.grpc.SearchRangeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public example.myapp.inventory.grpc.SearchRangeResponse buildPartial() {
      example.myapp.inventory.grpc.SearchRangeResponse result = new example.myapp.inventory.grpc.SearchRangeResponse(this);
      int from_bitField0_ = bitField0_;
      if (recordsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          records_ = java.util.Collections.unmodifiableList(records_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof example.myapp.inventory.grpc.SearchRangeResponse) {
        return mergeFrom((example.myapp.inventory.grpc.SearchRangeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(example.myapp.inventory.grpc.SearchRangeResponse other) {
      if (other == example.myapp.inventory.grpc.SearchRangeResponse.getDefaultInstance()) return this;
      if (recordsBuilder_ == null) {
        if (!other.records_.isEmpty()) {
          if (records_.isEmpty()) {
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecordsIsMutable();
            records_.addAll(other.records_);
          }
          onChanged();
        }
      } else {
        if (!other.records_.isEmpty()) {
          if (recordsBuilder_.isEmpty()) {
            recordsBuilder_.dispose();
            recordsBuilder_ = null;
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recordsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecordsFieldBuilder() : null;
          } else {
            recordsBuilder_.addAllMessages(other.records_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      example.myapp.inventory.grpc.SearchRangeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (example.myapp.inventory.grpc.SearchRangeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<example.myapp.inventory.grpc.InventoryRecord> records_ =
      java.util.Collections.emptyList();
    private void ensureRecordsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        records_ = new java.util.ArrayList<example.myapp.inventory.grpc.InventoryRecord>(records_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        example.myapp.inventory.grpc.InventoryRecord, example.myapp.inventory.grpc.InventoryRecord.Builder, example.myapp.inventory.grpc.InventoryRecordOrBuilder> recordsBuilder_;

    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public java.util.List<example.myapp.inventory.grpc.InventoryRecord> getRecordsList() {
      if (recordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(records_);
      } else {
        return recordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public int getRecordsCount() {
      if (recordsBuilder_ == null) {
        return records_.size();
      } else {
        return recordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public example.myapp.inventory.grpc.InventoryRecord getRecords(int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);
      } else {
        return recordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder setRecords(
        int index, example.myapp.inventory.grpc.InventoryRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.set(index, value);
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder setRecords(
        int index, example.myapp.inventory.grpc.InventoryRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder addRecords(example.myapp.inventory.grpc.InventoryRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder addRecords(
        int index, example.myapp.inventory.grpc.InventoryRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(index, value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder addRecords(
        example.myapp.inventory.grpc.InventoryRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder addRecords(
        int index, example.myapp.inventory.grpc.InventoryRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends example.myapp.inventory.grpc.InventoryRecord> values) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, records_);
        onChanged();
      } else {
        recordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public Builder removeRecords(int index) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.remove(index);
        onChanged();
      } else {
        recordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public example.myapp.inventory.grpc.InventoryRecord.Builder getRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public example.myapp.inventory.grpc.InventoryRecordOrBuilder getRecordsOrBuilder(
        int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);  } else {
        return recordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public java.util.List<? extends example.myapp.inventory.grpc.InventoryRecordOrBuilder> 
         getRecordsOrBuilderList() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(records_);
      }
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public example.myapp.inventory.grpc.InventoryRecord.Builder addRecordsBuilder() {
      return getRecordsFieldBuilder().addBuilder(
          example.myapp.inventory.grpc.InventoryRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public example.myapp.inventory.grpc.InventoryRecord.Builder addRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().addBuilder(
          index, example.myapp.inventory.grpc.InventoryRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .InventoryRecord records = 1;</code>
     */
    public java.util.List<example.myapp.inventory.grpc.InventoryRecord.Builder> 
         getRecordsBuilderList() {
      return getRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        example.myapp.inventory.grpc.InventoryRecord, example.myapp.inventory.grpc.InventoryRecord.Builder, example.myapp.inventory.grpc.InventoryRecordOrBuilder> 
        getRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            example.myapp.inventory.grpc.InventoryRecord, example.myapp.inventory.grpc.InventoryRecord.Builder, example.myapp.inventory.grpc.InventoryRecordOrBuilder>(
                records_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SearchRangeResponse)
  }

  // @@protoc_insertion_point(class_scope:SearchRangeResponse)
  private static final example.myapp.inventory.grpc.SearchRangeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new example.myapp.inventory.grpc.SearchRangeResponse();
  }

  public static example.myapp.inventory.grpc.SearchRangeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchRangeResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchRangeResponse>() {
    @java.lang.Override
    public SearchRangeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchRangeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchRangeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchRangeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public example.myapp.inventory.grpc.SearchRangeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

