// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

package example.myapp.inventory.grpc;

public interface UpdateInventoryAttributeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateInventoryAttributeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keyName = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string keyName = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string attributeName = 2;</code>
   */
  java.lang.String getAttributeName();
  /**
   * <code>string attributeName = 2;</code>
   */
  com.google.protobuf.ByteString
      getAttributeNameBytes();

  /**
   * <code>string newValue = 3;</code>
   */
  java.lang.String getNewValue();
  /**
   * <code>string newValue = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewValueBytes();
}
